### ISSUE TITLE
Handled object annotations

### ISSUE THREAD

**Issue by ghost** [google-deepmind/perception_test#16]
Hello. I am mostly interested in handled object instead of all of them inside the scene for object tracking. Have you structured the annotations in a way that is possible to get the handled object only? Instead of tracking the whole pool of object.
Thank you!

**Comment by sgjheywa** [comment]
Hi, 

In the action and sound [annotations](https://github.com/google-deepmind/perception_test#perception-test-annotations) we have a label 'parent_objects' which relates each action/sound to object track IDs. It should be possible to get handled objects only using this data.

Does this answer your question? Thanks!

**Comment by samuele-ruffino** [comment]
Great! Could work. Is the first one (since there might be mutiples) always the handles objects or the order does not metter? Because maybe there are multiple active object in the scene.

**Comment by viorik** [comment]
All the object ids that appear under 'parent_objects' for an action segment are involved in the corresponding action in the time interval when that action happens, e.g. for an action like "taking <something> out of <something>", there should be 2 parent objects corresponding to the 2 "somethings" in the action template name. We instructed the annotators to put the object ids in the order in which they appear in the action name, but this might be a bit noisy; for example, if a person takes a book out of a backpack, the action segment should have as parent_objects: id_book, id_backpack.

The same applies for sounds.

Hope this answers your question?

**Comment by viorik** [comment]
"taking *something* out of *something*"

**Comment by samuele-ruffino** [comment]
Ok great! It does work. Maybe one last point, I am trying to use both SOT and action annotation files 9valid set), but apparently there are missing videos for one task and vice-versa. Should they coincide or it could be ?

**Comment by viorik** [comment]
All videos have object tracks annotations. It is possible that some videos do not appear in the actions set because they don’t have action annotations. For example, there are some change detection videos where the camera is looking at a table with some objects on it, then the camera looks away, then comes back to the table after a few seconds. Some actions may have happened in the meantime involving the objects on the table, but they were not seen by the camera, hence no action annotations.

**Comment by samuele-ruffino** [comment]
But for the SOT challange specifically, is the challange benchmark (sot_valid_annotations_challenge2023.zip, 1000 videos) a subset of temporal action localization one (challenge_action_localisation_valid_annotations.zip)? Because I would like to prepocess the first data based on info that I get from the respective, but I am not sure if the two sets are overlapping or not (different subsets from valid set). Thank you!

**Comment by viorik** [comment]
The overlap is not guaranteed. The 1000 videos for SOT challenge have been sampled randomly from the entire validation set, independent of the action challenge. But you can access the entire training and validation sets for SOT using this repository, and in that way, all action videos will have corresponding SOT videos.
